version: "3.3"

services:
  mongodb:
    image: mongo:6.0.2
    restart: always
    env_file: .env
    volumes:
      - ./mongodb-data:/data/db
    ports:
      - 27017:27017

  mongodb-ui:
    image: mongo-express
    restart: always
    env_file: .env
    ports:
      - 8081:8081

  bot:
    build:
      dockerfile: ./Dockerfile
      context: .
    restart: always
    depends_on:
      - mongodb
    env_file:
      - .env
