services:
  bot:
    build:
      dockerfile: ./Dockerfile
      context: .
    restart: always
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:latest
    restart: always
    volumes:
      - ./redis/data:/data
    env_file:
      - path: .env
    ports:
      - '6379:6379'
