services:
  bot:
    container_name: where-my-podcast-bot
    build:
      dockerfile: ./Dockerfile
      context: .
    restart: always
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - ./downloads:/app/downloads

  redis:
    image: redis:latest
    container_name: where-my-podcast-cache
    restart: always
    volumes:
      - ./redis/data:/data
    env_file:
      - .env
    ports:
      - '6379:6379'
